import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

import StoreProvider from "@/app/_components/StoreProvider";
import { Session } from "next-auth";
import { ReactNode } from "react";

type Props = {
  session?: Session | null;
  children: ReactNode;
  modal: ReactNode;
};

const notoSansKr = Noto_Sans_KR({
  weight: ["500"],
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: Props) {
  return (
    <html lang="ko">
      <head></head>
      <body>
        <StoreProvider>
          <div className={`h-dvh w-dvw ${(notoSansKr.className, "w-dvw")}`}>
            {modal}
            <section>{children}</section>
            <footer className="flex h-[70px] w-auto items-center justify-center bg-[#f9f9f9]">
              Copyright&copy;2024 All rights reserved
            </footer>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
