import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

const notoSansKr = Noto_Sans_KR({
  weight: ["500"],
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head></head>
      <body>
        <div className={(notoSansKr.className, "w-dvw")}>
          <section>{children}</section>
          <footer className="flex h-[70px] w-auto items-center justify-center bg-[#f9f9f9]">
            Copyright&copy;2024 All rights reserved
          </footer>
        </div>
      </body>
    </html>
  );
}
